services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: app
    ports:
      - 8000:8000
    networks:
      fastapi-promgraf:
        ipv4_address: 172.16.238.10
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.54.1
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      fastapi-promgraf:
        ipv4_address: 172.16.238.11

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    networks:
      fastapi-promgraf:
        ipv4_address: 172.16.238.12

networks:
  fastapi-promgraf:
    name: fastapi-promgraf
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
